# Generated by Django 4.2.18 on 2025-01-30 00:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0005_article_user_comment_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='name',
        ),
    ]
